sudo: required
dist: xenial
language: c++
services:
  - docker

notifications:
    slack: depthmapx:B3CKNlNDLrNz1vSOU5yoQQqA
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG9yYW5nZS12ZXJ0ZXglM0FtYXRyaXgub3JnLyUyMUVZQUZRaEVrV3lDZm1hcm9QaCUzQW1hdHJpeC5vcmc"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never


script:
  - docker run --security-opt seccomp:unconfined --user $UID -v $PWD:/mnt/code blackseamonster/depthmapx-buildenv:0.3 bash -c ci/build.sh
