name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --security-opt seccomp:unconfined --user $UID -v $GITHUB_WORKSPACE:/mnt/code blackseamonster/depthmapx-buildenv:0.3 bash -c ci/build.sh
